---
output:
  html_document:
    toc: true
    toc_depth: 3
---

<div class="container">
<div class="jumbotron" style="margin-left:-15px">
<h1 class="title">Workshop</h1>
<h2 class="subtitle">Querying large-scale online datasets: SQL and Google BigQuery</h2>
<p>London School of Economics, December 6th 2018</p>
</div>
</div>

The volume and heterogeneity of the new datasets available in the digital age present unprecedented opportunities for social scientists, but also new methodological challenges. Computing a simple average for a variable across groups can take minutes when a researcher is working with government records, large-scale survey studies or social media datasets with millions of rows. The goal of this workshop is to learn how to overcome challenges associated to massive-scale online databases. We will learn the basics of SQL, a language designed to query relational databases that is currently employed by most tech companies; and how to use it from R using the DBI package. From all the available options to store online databases, we will focus on BigQuery, which relies on Google’s infrastructure to efficiently store and query databases at scale. We will learn how to process, upload, and query databases of up to a billion rows in a matter of seconds, and how to export the results of our queries.

The workshop follows a "learning-by-doing" approach, with short guided coding sessions followed by data challenges that will prompt participants to practice what they just learned. 

# Instructor

<table class = "table table-striped">
<tr>
<td><a href="http://www.pablobarbera.com"><strong>Pablo Barberá</strong></a></td>
<td><a href="mailto:P.Barbera@lse.ac.uk">P.Barbera@lse.ac.uk</a></td>
<td><a href="https://www.twitter.com/p_barbera">@p_barbera</a></td>
</tr>
</table>


# Schedule

<table class = "table table-striped table-hover">
<tr>
<td><b>Session 1</b></td>
<td>December 6, 2018</td>
<td> 10&ndash;12:00 </td>
</tr>
<tr>
<td><b>Session 2</b></td>
<td>December 6, 2018</td>
<td> 14&ndash;16:00 </td>
</tr>
</table>


# Prerequisites

Familiarity with the R statistical programming language is desirable but not required. Students are expected to bring a laptop to class and follow along the coding section of each session.


# Software 

This course will use [R](https://www.r-project.org/), which is a free and open-source programming language primarily used for statistics and data analysis. We will also use [RStudio](https://www.rstudio.com/), which is an easy-to-use interface to R. 

Installing R or RStudio prior to the workshop is not necessary. The instructor will provide individual login details to an RStudio Server that all workshop participants can access to run their code.

# License and credit

Science should be open, and this course builds up other open licensed material, so unless otherwise noted, all materials for this class are licensed under a <a rel="license" href="https://creativecommons.org/licenses/by/4.0/">Creative Commons Attribution 4.0 International License</a>.

The layout for this website was designed by [Jeffrey Arnold](http://www.jrnold.me/) (thanks!).

The source for the materials of this course is on GitHub at <a href="https://github.com/pablobarbera/SQL-workshop">pablobarbera/SQL-workshop</a>

# Feedback

If you have any feedback on the course or find any typos or errors in this website go to [issues](https://github.com/pablobarbera/SQL-workshop/issues), click on the "New Issue" button to create a new issue, and add your suggestion or describe the problem.


